name: KMP Toolchain

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S_NAME: ${{ secrets.S_NAME }}
          S_KEY: ${{ secrets.S_KEY }}